# Generated by Django 4.1.1 on 2022-11-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('mainCategory', models.CharField(max_length=100)),
                ('subCategory', models.CharField(max_length=300)),
                ('imageUrl', models.URLField()),
                ('details', models.TextField(max_length=300)),
                ('price', models.IntegerField()),
                ('newProduct', models.BooleanField(default=False)),
                ('averageScore', models.FloatField(default=0)),
                ('tags', models.ManyToManyField(related_name='products', to='product.tag')),
            ],
        ),
    ]
