# Generated by Django 4.1.2 on 2022-11-13 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productTag', to='product.product')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductTag', to='product.tag')),
            ],
        ),
        migrations.RemoveField(
            model_name='rate',
            name='scores',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', through='product.ProductTag', to='product.tag'),
        ),
    ]
