# Generated by Django 4.1.2 on 2022-11-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='scores',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
