# Generated by Django 4.1.1 on 2022-12-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_rate_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rateCount',
            field=models.IntegerField(default=0),
        ),
    ]
