# Generated by Django 4.1.1 on 2022-12-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_ratecount'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='averageScore',
            field=models.FloatField(default=0),
        ),
    ]
