# Generated by Django 4.1.1 on 2022-11-07 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.IntegerField(default=0)),
                ('taste', models.IntegerField(default=0)),
                ('question', models.IntegerField(max_length=30)),
                ('loginState', models.BooleanField(default=False)),
            ],
        ),
    ]
