# Generated by Django 4.1.1 on 2022-11-07 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='question',
        ),
        migrations.RemoveField(
            model_name='user',
            name='taste',
        ),
    ]
